name: Run Qafood on BrowserStack

on:
  workflow_dispatch:
    inputs:
      spec:
        description: 'Qual spec deseja rodar? (ex: specs/login_test.ts)'
        required: true
        default: 'specs/login_test.ts'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run CodeceptJS on BrowserStack
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_APP: ${{ secrets.BROWSERSTACK_APP }}
        run: |
          npx codeceptjs run -c codecept.conf.bs.ts ${{ github.event.inputs.spec }} --steps
