name: Run Login QAfood on BrowserStack

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Login Spec on BrowserStack
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_APP: ${{ secrets.BROWSERSTACK_APP }}
        run: |
          # Usando binário local do CodeceptJS para evitar problemas de permissão
          ./node_modules/.bin/codeceptjs run -c codecept.conf.bs.ts specs/login_test.ts --steps
